### ISSUE TITLE
Add full namespace to identifiers?

### ISSUE THREAD

**Issue by PeterPanino** [delphidabbler/unit2ns#2]
I would be interested in a plugin that adds the full namespace to all identifiers in a unit (or inside the selection). For example:

**FormatDateTime** will be converted to **System.SysUtils.FormatDateTime**, etc.

Is such a feature possible?

**Comment by delphidabbler** [comment]
I guess you mean a plug-in for the Delphi IDE?

## Short answer 1

Not with Unit2NS!

## Short answer 2

Probably with the modern  tools API that come with Delphi, but it would be far from trivial.

## Longer Answer

The last time I hacked the IDE it was with Delphi 7, and the Tools API has apparently completely changed since then, so I may be way off here.

I can envisage two approaches:

1. Some convoluted code that watches what you're typing and pops up a widget to suggest a "namespace". That'd be hard and I can see some danger of interfering with intellisense.
2. Code that you activate by placing the cursor (or selection, as you suggested) on an identifier and press some key combination. That would activate some kind of lookup a bit like Unit2NS does, but using identifiers instead of units. I think there would be three possible outcomes:
  a. The identifier is not known - do nothing
  b. The identifier is found in just one unit - prepend the fully specified unit name
  c. The same identifier occurs is more than one unit - pop up a choice of units, select one & prepend that.

Phew!

A couple of major problems I can foresee right now:

1. Where to get the list of valid identifiers from? Delphi obviously can do this because it can suggest them, but I don't know if the Tools API can access that list.
2. This could only work for units that were in a suitable uses clause in the code, otherwise there would a need to get and maintain a huge list of all identifiers in all units!

Unit2NS uses the second approach, but since it only knows about units, to list is much smaller.

## Summary

I guess it _could_ be done, but it would be a complex undertaking and it would need a good grasp of the Tools API.

It's not something that Unit2NS could handle, even if a plug-in wasn't used, because of the need to maintain a huge list of all the identifiers in the RTL, VCL etc.

**Comment by delphidabbler** [comment]
This is a great idea, but, after further thought, it's definitely not something I can coax Unit2NS into doing.

Reluctantly closing this issue as a result.
